# Generated by Django 5.1.5 on 2025-01-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session1Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('habit_goal_confidence', models.IntegerField()),
                ('self_performance_confidence', models.IntegerField()),
                ('teammate_performance_confidence', models.IntegerField()),
                ('goal_success_rate', models.IntegerField()),
                ('school_discipline', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session2Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('leadership_confidence_pre', models.IntegerField()),
                ('leadership_confidence_post', models.IntegerField()),
                ('accountability_pre', models.IntegerField()),
                ('accountability_post', models.IntegerField()),
                ('responsibility_pre', models.IntegerField()),
                ('responsibility_post', models.IntegerField()),
                ('proactiveness_pre', models.IntegerField()),
                ('proactiveness_post', models.IntegerField()),
                ('team_culture_pre', models.IntegerField()),
                ('team_culture_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session3Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('responsibility_pre', models.IntegerField()),
                ('responsibility_post', models.IntegerField()),
                ('focus_control_pre', models.IntegerField()),
                ('focus_control_post', models.IntegerField()),
                ('follow_through_pre', models.IntegerField()),
                ('follow_through_post', models.IntegerField()),
                ('team_accountability_pre', models.IntegerField()),
                ('team_accountability_post', models.IntegerField()),
                ('conscious_decision_pre', models.IntegerField()),
                ('conscious_decision_post', models.IntegerField()),
                ('accountability_pre', models.IntegerField()),
                ('accountability_post', models.IntegerField()),
                ('enforcer_pre', models.IntegerField()),
                ('enforcer_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session4Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('confidence_success_pre', models.IntegerField()),
                ('confidence_success_post', models.IntegerField()),
                ('best_athlete_pre', models.IntegerField()),
                ('best_athlete_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Session5Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255)),
                ('lead_by_example_pre', models.IntegerField()),
                ('lead_by_example_post', models.IntegerField()),
                ('learning_growth_pre', models.IntegerField()),
                ('learning_growth_post', models.IntegerField()),
                ('leadership_confidence_pre', models.IntegerField()),
                ('leadership_confidence_post', models.IntegerField()),
                ('communication_confidence_pre', models.IntegerField()),
                ('communication_confidence_post', models.IntegerField()),
            ],
        ),
    ]
